### ISSUE TITLE
An error when uploading a photo

### ISSUE THREAD

**Issue by mednisrihards** [chladog/payload-webp#14]
Ive set the "sharp": "^0.31.3" in package.json just like sharp listed in payload dependencies and this happens when I'm uploading an image.

Can anybody tell me why this is happening please?

/home/node/app/node_modules/payload-webp/lib/WebpCollection.js:33
2023-07-13 20:49:39             op = body.call(thisArg, _);
2023-07-13 20:49:39                        ^
2023-07-13 20:49:39 TypeError: Cannot read properties of undefined (reading 'indexOf')
2023-07-13 20:49:39     at /home/node/app/node_modules/payload-webp/lib/WebpCollection.js:106:45
2023-07-13 20:49:39     at step (/home/node/app/node_modules/payload-webp/lib/WebpCollection.js:33:23)
2023-07-13 20:49:39     at Object.next (/home/node/app/node_modules/payload-webp/lib/WebpCollection.js:14:53)
2023-07-13 20:49:39     at /home/node/app/node_modules/payload-webp/lib/WebpCollection.js:8:71
2023-07-13 20:49:39     at new Promise (<anonymous>)
2023-07-13 20:49:39     at __awaiter (/home/node/app/node_modules/payload-webp/lib/WebpCollection.js:4:12)
2023-07-13 20:49:39     at convertImages (/home/node/app/node_modules/payload-webp/lib/WebpCollection.js:100:50)
2023-07-13 20:49:39     at /home/node/app/node_modules/payload-webp/lib/WebpCollection.js:138:21
2023-07-13 20:49:39     at step (/home/node/app/node_modules/payload-webp/lib/WebpCollection.js:33:23)
2023-07-13 20:49:39     at Object.next (/home/node/app/node_modules/payload-webp/lib/WebpCollection.js:14:53)
2023-07-13 20:49:39 [nodemon] app crashed - waiting for file changes before starting...

**Comment by mednisrihards** [comment]
Closed because nobody gives a damn sht about it
